### ISSUE TITLE
Package ‘ncdf4.helpers’ was removed from the CRAN repository

### ISSUE THREAD

**Issue by bouweandela** [pacificclimate/ncdf4.helpers#1]
This package was recently removed from CRAN, https://cran.r-project.org/web/packages/ncdf4.helpers/

```
Package ‘ncdf4.helpers’ was removed from the CRAN repository.

Formerly available versions can be obtained from the archive.

Archived on 2019-11-16 as check problems were not corrected in time. 
```

Related to https://github.com/pacificclimate/climdex.pcic.ncdf/issues/16.

**Comment by corviday** [comment]
I have been working on returning this package to CRAN, but I have so far been unable to reproduce the errors CRAN is reporting with this package, so it has been slow going.

**Comment by corviday** [comment]
The issue seems to be that the `project()` function in the `proj4` library, as used in some of our tests, behaves differently on different systems. Specifically, the results it returns on CRAN's Debian test system do not match the results it returns on CRAN's Windows test system, or any of the other systems I have checked with. This causes our tests that use proj4 to fail on CRAN's Debian test system.

I'm hoping this turns out to be an issue in the way we include or invoke `proj4`, rather than an error in `proj4` itself.

**Comment by bouweandela** [comment]
Great to hear that you're making progress on this!

**Comment by corviday** [comment]
Unfortunately, I have not been able to figure out why, exactly, `project()` returns different values for some general oblique transformations run on Debian, as compared to other operating systems (CentOS, Windows, Ubuntu, MacOS, Fedora). Since `proj4` isn't, strictly speaking, needed to run this package, I ultimately just rewrote the tests to skip calls to `project()` when run on a Linux system. I have resubmitted to CRAN.

**Comment by thiagoveloso** [comment]
On Linux, it can still be installed with `R CMD INSTALL ncdf4.helpers_0.3-3.tar.gz` (using the "latest" archived version available at https://cran.r-project.org/src/contrib/Archive/ncdf4.helpers/).

**Comment by bouweandela** [comment]
Thank you for putting in the effort to getting the package published on CRAN again!
