### ISSUE TITLE
Parsing of time units fails with multiple white spaces

### ISSUE THREAD

**Issue by lochbika** [pacificclimate/ncdf4.helpers#8]
Hi,

version: 0.3-6

I just found out that the parsing of the time unit string in the `nc.get.time.series` function fails if the string contains multiple spaces. For instance:
```
days since 850-1-1 00:00:00
```
is parsed perfectly fine. However
```
days since           850-1-1 00:00:00
```
throws an error: 

```
Error in as.POSIXlt.character(x, tz, format, ...) : 
  character string is not in a standard unambiguous format
```
The source of the error is the two white spaces between "since" and "850-1-1". I guess `strsplit` returns empty elements in the split vector `time.split`.

A possible workaround could be to first run 
`time.split <- strsplit(f$dim$time$units, " ")[[1]]`
and then drop empty elements with something like
`time.split <- time.split[time.split != ""]`

Cheers,
Kai

P.S. great work! I love the comments in the source code ;)

**Comment by jameshiebert** [comment]
Hey Kai,

Hmmm, that's definitely an unusual case. Not sure why someone would have arbitrarily long space listed in their time units. That's not explicitly covered by [the CF Conventions spec](https://cfconventions.org/Data/cf-conventions/cf-conventions-1.9/cf-conventions.html#time-coordinate).

Admittedly the canonical implementation of units parsing, `udunits2`, *does* parse your case:

```R
> library(udunits2)
udunits system database read
> ud.is.parseable('days since 850-1-1 00:00:00')
[1] TRUE
> ud.is.parseable('days since   850-1-1 00:00:00')
[1] TRUE
```

And it since `strsplit` takes a regular expression, it's easy to split on one or more spaces with a one character change:

```R
> strsplit('days since   850-1-1 00:00:00', ' +')
[[1]]
[1] "days"     "since"    "850-1-1"  "00:00:00"
```

I'll push a patch, but it's unlikely that it will get incorporated into a release in the near future. Thanks for the report, though.

**Comment by lochbika** [comment]
Hi James,
thanks for the quick reply. The solution with regex is great!

> Hmmm, that's definitely an unusual case. Not sure why someone would have arbitrarily long space listed in their time units. That's not explicitly covered by the CF Conventions spec.

I also wouldn't expect it. But it happened while I was reading some CMIP5 output into R. It was just a double space which is apparently enough, however.

Thanks for the fix.
